version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-analyzer-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend-service:8080/api
      - REACT_APP_KEYCLOAK_URL=http://keycloak-service:8080/auth
      - REACT_APP_KEYCLOAK_REALM=web-analyzer
      - REACT_APP_KEYCLOAK_CLIENT_ID=web-analyzer-frontend
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge